# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'PaidyCheckoutSample' do

pod 'CryptoSwift'
use_frameworks!

end

target 'PaidyCheckoutSampleTests' do

end

